import 'package:flutter/material.dart';
import 'package:flutter_animate/flutter_animate.dart';
import '../core/theme.dart';
import '../widgets/glass_card.dart';
import 'daily_task_screen.dart';
import 'progress_stats_screen.dart';

class SkillRoadmapScreen extends StatefulWidget {
  final String skillName;
  final String skillType;

  const SkillRoadmapScreen({
    super.key,
    required this.skillName,
    required this.skillType,
  });

  @override
  State<SkillRoadmapScreen> createState() => _SkillRoadmapScreenState();
}

class _SkillRoadmapScreenState extends State<SkillRoadmapScreen> {
  int currentDay = 1;
  int completedDays = 7;
  int currentStreak = 7;
  int totalXP = 1250;
  int currentLevel = 3;

  List<DailyTask> _getDailyTasks() {
    // This would be generated by AI in production
    return List.generate(30, (index) {
      final day = index + 1;
      final isCompleted = day <= completedDays;
      final isCurrent = day == currentDay;
      final isLocked = day > currentDay;

      return DailyTask(
        day: day,
        title: _getTaskTitle(day),
        description: _getTaskDescription(day),
        estimatedMinutes: 15,
        xpReward: 50,
        isCompleted: isCompleted,
        isCurrent: isCurrent,
        isLocked: isLocked,
        difficulty: _getDifficulty(day),
      );
    });
  }

  String _getTaskTitle(int day) {
    if (day <= 7) return 'Week 1: Fundamentals';
    if (day <= 14) return 'Week 2: Core Concepts';
    if (day <= 21) return 'Week 3: Advanced Topics';
    return 'Week 4: Mastery';
  }

  String _getTaskDescription(int day) {
    final tasks = {
      1: 'Introduction to ${widget.skillName} basics',
      2: 'Understanding core principles',
      3: 'First hands-on practice',
      4: 'Building muscle memory',
      5: 'Common patterns and techniques',
      6: 'Error handling and debugging',
      7: 'Week 1 review and practice',
      8: 'Intermediate concepts',
      9: 'Advanced patterns',
      10: 'Real-world application',
      // Add more as needed
    };
    return tasks[day] ?? 'Day $day: Continue your journey';
  }

  String _getDifficulty(int day) {
    if (day <= 7) return 'Beginner';
    if (day <= 14) return 'Intermediate';
    if (day <= 21) return 'Advanced';
    return 'Expert';
  }

  @override
  Widget build(BuildContext context) {
    final tasks = _getDailyTasks();
    final progressPercent = completedDays / 30;

    return Scaffold(
      body: Container(
        decoration: const BoxDecoration(
          gradient: AppGradients.main,
        ),
        child: Stack(
          children: [
            // Background orbs
            Positioned(
              top: -100,
              right: -100,
              child: AnimatedOrb(color: AppColors.teal, size: 300),
            ),
            Positioned(
              bottom: -150,
              left: -150,
              child: AnimatedOrb(color: AppColors.purple, size: 350),
            ),

            SafeArea(
              child: CustomScrollView(
                slivers: [
                  // App Bar
                  SliverAppBar(
                    backgroundColor: Colors.transparent,
                    leading: IconButton(
                      icon: const Icon(Icons.arrow_back_ios, color: AppColors.textPrimary),
                      onPressed: () => Navigator.pop(context),
                    ),
                    title: Text(
                      widget.skillName,
                      style: Theme.of(context).textTheme.headlineMedium,
                    ),
                    actions: [
                      IconButton(
                        icon: const Icon(Icons.insights_rounded, color: AppColors.textPrimary),
                        onPressed: () {
                          Navigator.push(
                            context,
                            MaterialPageRoute(
                              builder: (_) => ProgressStatsScreen(
                                skillName: widget.skillName,
                              ),
                            ),
                          );
                        },
                      ),
                      // IconButton(
                      //   icon: const Icon(Icons.account_tree_rounded, color: AppColors.textPrimary),
                      //   onPressed: () {
                      //     Navigator.push(
                      //       context,
                      //       MaterialPageRoute(
                      //         builder: (_) => SkillTreeScreen(
                      //           skillName: widget.skillName,
                      //         ),
                      //       ),
                      //     );
                      //   },
                      // ),
                    ],
                  ),

                  SliverPadding(
                    padding: const EdgeInsets.all(24),
                    sliver: SliverList(
                      delegate: SliverChildListDelegate([
                        // Header Stats
                        _buildHeaderStats(progressPercent),
                        const SizedBox(height: 32),

                        // Current Task Highlight
                        _buildCurrentTaskCard(tasks[currentDay - 1]),
                        const SizedBox(height: 32),

                        // Week Sections
                        _buildWeekSection('Week 1: Fundamentals', tasks.sublist(0, 7), 1),
                        const SizedBox(height: 24),
                        _buildWeekSection('Week 2: Core Concepts', tasks.sublist(7, 14), 2),
                        const SizedBox(height: 24),
                        _buildWeekSection('Week 3: Advanced Topics', tasks.sublist(14, 21), 3),
                        const SizedBox(height: 24),
                        _buildWeekSection('Week 4: Mastery', tasks.sublist(21, 30), 4),
                        const SizedBox(height: 40),
                      ]),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildHeaderStats(double progressPercent) {
    return Column(
      children: [
        // Progress Overview
        GlassContainer(
          child: Padding(
            padding: const EdgeInsets.all(24),
            child: Column(
              children: [
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Text(
                      '30-Day Journey',
                      style: Theme.of(context).textTheme.headlineSmall?.copyWith(
                        fontWeight: FontWeight.w900,
                      ),
                    ),
                    Container(
                      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                      decoration: BoxDecoration(
                        gradient: AppGradients.teal,
                        borderRadius: BorderRadius.circular(20),
                        boxShadow: [
                          BoxShadow(
                            color: AppColors.teal.withValues(alpha: 0.3),
                            blurRadius: 12,
                            offset: const Offset(0, 4),
                          ),
                        ],
                      ),
                      child: Row(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          const Icon(Icons.local_fire_department_rounded, color: Colors.white, size: 16),
                          const SizedBox(width: 4),
                          Text(
                            '$currentStreak Day Streak',
                            style: const TextStyle(
                              color: Colors.white,
                              fontWeight: FontWeight.w800,
                              fontSize: 12,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 20),

                // Progress Bar
                Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Text(
                          'Day $completedDays of 30',
                          style: Theme.of(context).textTheme.bodyLarge?.copyWith(
                            fontWeight: FontWeight.w700,
                            color: AppColors.textPrimary,
                          ),
                        ),
                        Text(
                          '${(progressPercent * 100).toInt()}%',
                          style: Theme.of(context).textTheme.bodyLarge?.copyWith(
                            fontWeight: FontWeight.w900,
                            color: AppColors.teal,
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 12),
                    ClipRRect(
                      borderRadius: BorderRadius.circular(10),
                      child: LinearProgressIndicator(
                        value: progressPercent,
                        backgroundColor: AppColors.surface.withValues(alpha: 0.3),
                        valueColor: const AlwaysStoppedAnimation<Color>(AppColors.teal),
                        minHeight: 12,
                      ),
                    ),
                  ],
                ),

                const SizedBox(height: 20),

                // Stats Row
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceAround,
                  children: [
                    _buildStatItem(Icons.emoji_events_rounded, 'Level $currentLevel', AppColors.amber),
                    Container(width: 1, height: 40, color: AppColors.surface.withValues(alpha: 0.3)),
                    _buildStatItem(Icons.stars_rounded, '$totalXP XP', AppColors.purple),
                    Container(width: 1, height: 40, color: AppColors.surface.withValues(alpha: 0.3)),
                    _buildStatItem(Icons.check_circle_rounded, '$completedDays Done', AppColors.success),
                  ],
                ),
              ],
            ),
          ),
        ).animate().fadeIn(duration: 600.ms).slideY(begin: 0.2),
      ],
    );
  }

  Widget _buildStatItem(IconData icon, String label, Color color) {
    return Column(
      children: [
        Icon(icon, color: color, size: 24),
        const SizedBox(height: 4),
        Text(
          label,
          style: TextStyle(
            color: AppColors.textSecondary,
            fontSize: 12,
            fontWeight: FontWeight.w700,
          ),
        ),
      ],
    );
  }

  Widget _buildCurrentTaskCard(DailyTask task) {
    return GlassCard(
      gradient: AppGradients.tealPurple,
      child: InkWell(
        onTap: () {
          Navigator.push(
            context,
            MaterialPageRoute(
              builder: (_) => DailyTaskScreen(task: task, skillName: widget.skillName),
            ),
          );
        },
        borderRadius: BorderRadius.circular(16),
        child: Padding(
          padding: const EdgeInsets.all(24),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  Container(
                    padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                    decoration: BoxDecoration(
                      color: Colors.white.withValues(alpha: 0.2),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: Text(
                      'TODAY',
                      style: const TextStyle(
                        color: Colors.white,
                        fontSize: 10,
                        fontWeight: FontWeight.w900,
                        letterSpacing: 1,
                      ),
                    ),
                  ),
                  const Spacer(),
                  Container(
                    padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                    decoration: BoxDecoration(
                      color: Colors.white.withValues(alpha: 0.2),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        const Icon(Icons.timer_outlined, color: Colors.white, size: 14),
                        const SizedBox(width: 4),
                        Text(
                          '${task.estimatedMinutes} min',
                          style: const TextStyle(
                            color: Colors.white,
                            fontSize: 11,
                            fontWeight: FontWeight.w700,
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 16),
              Text(
                'Day ${task.day}',
                style: const TextStyle(
                  color: Colors.white70,
                  fontSize: 14,
                  fontWeight: FontWeight.w600,
                ),
              ),
              const SizedBox(height: 8),
              Text(
                task.description,
                style: const TextStyle(
                  color: Colors.white,
                  fontSize: 22,
                  fontWeight: FontWeight.w900,
                  height: 1.2,
                ),
              ),
              const SizedBox(height: 16),
              Row(
                children: [
                  Expanded(
                    child: Container(
                      padding: const EdgeInsets.symmetric(vertical: 12),
                      decoration: BoxDecoration(
                        color: Colors.white,
                        borderRadius: BorderRadius.circular(12),
                      ),
                      child: Center(
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            const Icon(Icons.play_arrow_rounded, color: AppColors.purple, size: 20),
                            const SizedBox(width: 4),
                            Text(
                              'Start Task',
                              style: TextStyle(
                                color: AppColors.purple,
                                fontWeight: FontWeight.w900,
                                fontSize: 15,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ),
                  const SizedBox(width: 12),
                  Container(
                    padding: const EdgeInsets.all(12),
                    decoration: BoxDecoration(
                      color: Colors.white.withValues(alpha: 0.2),
                      borderRadius: BorderRadius.circular(12),
                    ),
                    child: const Icon(Icons.lightbulb_outline_rounded, color: Colors.white, size: 20),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    ).animate().fadeIn(duration: 600.ms, delay: 200.ms).slideY(begin: 0.2);
  }

  Widget _buildWeekSection(String title, List<DailyTask> tasks, int weekNumber) {
    final weekCompleted = tasks.every((t) => t.isCompleted);

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            Container(
              width: 8,
              height: 8,
              decoration: BoxDecoration(
                color: weekCompleted ? AppColors.success : AppColors.teal,
                shape: BoxShape.circle,
              ),
            ),
            const SizedBox(width: 12),
            Text(
              title,
              style: Theme.of(context).textTheme.titleLarge?.copyWith(
                fontWeight: FontWeight.w800,
              ),
            ),
            if (weekCompleted) ...[
              const SizedBox(width: 8),
              const Icon(Icons.check_circle_rounded, color: AppColors.success, size: 20),
            ],
          ],
        ),
        const SizedBox(height: 16),

        // Day Cards
        ...tasks.asMap().entries.map((entry) {
          final index = entry.key;
          return Padding(
            padding: const EdgeInsets.only(bottom: 12),
            child: _buildDayCard(entry.value).animate()
                .fadeIn(duration: 600.ms, delay: (400 + index * 50).ms)
                .slideX(begin: 0.1),
          );
        }),
      ],
    );
  }

  Widget _buildDayCard(DailyTask task) {
    Color statusColor;
    IconData statusIcon;

    if (task.isCompleted) {
      statusColor = AppColors.success;
      statusIcon = Icons.check_circle_rounded;
    } else if (task.isCurrent) {
      statusColor = AppColors.teal;
      statusIcon = Icons.play_circle_filled_rounded;
    } else if (task.isLocked) {
      statusColor = AppColors.textSecondary.withValues(alpha: 0.3);
      statusIcon = Icons.lock_rounded;
    } else {
      statusColor = AppColors.amber;
      statusIcon = Icons.circle_outlined;
    }

    return GlassContainer(
      color: task.isCurrent
          ? AppColors.teal.withValues(alpha: 0.05)
          : task.isLocked
          ? AppColors.surface.withValues(alpha: 0.02)
          : Colors.transparent,
      border: task.isCurrent
          ? Border.all(color: AppColors.teal.withValues(alpha: 0.5), width: 2)
          : null,
      child: InkWell(
        onTap: task.isLocked ? null : () {
          Navigator.push(
            context,
            MaterialPageRoute(
              builder: (_) => DailyTaskScreen(task: task, skillName: widget.skillName),
            ),
          );
        },
        borderRadius: BorderRadius.circular(16),
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Row(
            children: [
              // Day Number
              Container(
                width: 48,
                height: 48,
                decoration: BoxDecoration(
                  color: statusColor.withValues(alpha: 0.15),
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(
                    color: statusColor.withValues(alpha: 0.3),
                    width: 2,
                  ),
                ),
                child: Center(
                  child: Text(
                    '${task.day}',
                    style: TextStyle(
                      color: statusColor,
                      fontWeight: FontWeight.w900,
                      fontSize: 18,
                    ),
                  ),
                ),
              ),
              const SizedBox(width: 16),

              // Task Info
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      task.description,
                      style: Theme.of(context).textTheme.bodyLarge?.copyWith(
                        fontWeight: FontWeight.w700,
                        color: task.isLocked
                            ? AppColors.textSecondary.withValues(alpha: 0.5)
                            : AppColors.textPrimary,
                      ),
                      maxLines: 2,
                      overflow: TextOverflow.ellipsis,
                    ),
                    const SizedBox(height: 6),
                    Row(
                      children: [
                        Container(
                          padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                          decoration: BoxDecoration(
                            color: _getDifficultyColor(task.difficulty).withValues(alpha: 0.15),
                            borderRadius: BorderRadius.circular(6),
                          ),
                          child: Text(
                            task.difficulty,
                            style: TextStyle(
                              fontSize: 10,
                              fontWeight: FontWeight.w800,
                              color: _getDifficultyColor(task.difficulty),
                            ),
                          ),
                        ),
                        const SizedBox(width: 8),
                        Icon(Icons.timer_outlined, size: 12, color: AppColors.textSecondary),
                        const SizedBox(width: 4),
                        Text(
                          '${task.estimatedMinutes}m',
                          style: TextStyle(
                            fontSize: 11,
                            fontWeight: FontWeight.w600,
                            color: AppColors.textSecondary,
                          ),
                        ),
                        const SizedBox(width: 8),
                        Icon(Icons.stars_rounded, size: 12, color: AppColors.amber),
                        const SizedBox(width: 4),
                        Text(
                          '+${task.xpReward} XP',
                          style: TextStyle(
                            fontSize: 11,
                            fontWeight: FontWeight.w700,
                            color: AppColors.amber,
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),

              // Status Icon
              Icon(
                statusIcon,
                color: statusColor,
                size: 28,
              ),
            ],
          ),
        ),
      ),
    );
  }

  Color _getDifficultyColor(String difficulty) {
    switch (difficulty.toLowerCase()) {
      case 'beginner':
        return AppColors.success;
      case 'intermediate':
        return AppColors.amber;
      case 'advanced':
        return AppColors.purple;
      case 'expert':
        return AppColors.error;
      default:
        return AppColors.teal;
    }
  }
}

// Model Classes
class DailyTask {
  final int day;
  final String title;
  final String description;
  final int estimatedMinutes;
  final int xpReward;
  final bool isCompleted;
  final bool isCurrent;
  final bool isLocked;
  final String difficulty;

  DailyTask({
    required this.day,
    required this.title,
    required this.description,
    required this.estimatedMinutes,
    required this.xpReward,
    required this.isCompleted,
    required this.isCurrent,
    required this.isLocked,
    required this.difficulty,
  });
}